apiVersion: apps/v1
kind: Deployment
metadata:
  name: mediawiki-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mediawiki-db
  template:
    metadata:
      labels:
        app: mediawiki-db
    spec:
      containers:
      - name: mediawiki-db
        image: docker.io/sarvesh137/mediawiki:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        resources:
            limits:
              cpu: "0.5"
            requests:
              cpu: "0.25"
              
              
             
