apiVersion: v1
kind: Service
metadata:
  name: mediawiki-db
  labels:
    app: mediawiki-db
spec:
  selector:
    app: mediawiki-db
  ports:
  - port: 3000
    protocol: TCP
    nodePort: 30001
  type: LoadBalancer
