apiVersion: v1
kind: Service
metadata:
  name: mediawiki-app
  labels:
    app: mediawiki-app
spec:
  selector:
    app: mediawiki-app
  ports:
  - port: 3000
    protocol: TCP
    nodePort: 30001
  type: LoadBalancer